[package]
name = "matio-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi = { path = "sys", package = "matio-sys" }
num-traits = "0.2.14"
thiserror = "1.0.30"
