[package]
name = "matio-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi = { path = "sys", package = "matio-sys" }
nalgebra = { version = "0.31.0", optional = true }
num-traits = "0.2.14"
paste = "1.0.7"
thiserror = "1.0.30"
