[package]
name = "matio-rs"
version = "0.5.0"
edition = "2021"
authors = ["Rod Conan <rconan@gmto.org>"]
license = "MIT"
description = "Rust wrapper to MATLAB MAT file I/O library"
repository = "https://github.com/rconan/matio-rs"
documentation = "https://docs.rs/matio-rs"
readme = "README.md"
categories = ["api-bindings", "mathematics", "science"]

[dependencies]
ffi = { version = "0.2.1", path = "sys", package = "matio-rs-sys" }
nalgebra = { version = "0.31.0", optional = true }
paste = "1.0.7"
thiserror = "1.0.30"

[package.metadata.docs.rs]
all-features = true
